---
title: "Package 'cleanIGRA' Vignettes"
author: "Jackson Kwok"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{main_functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

### Key functionality 

This package is created to do only one task; it parses the raw IGRA data and converts them into an R dataframe. The two main functions are `clean_IGRA_v1` and `clean_IGRA_v2`; the former parses the IGRA v1 data (discontinued on May 31, 2019), and the latter parses the IGRA v2 data. Here are two examples.


#### IGRA v1 data
```{r, results = 'hide', cache = TRUE, message=FALSE}
# IGRA v1 data (.y2d, .dat, .mly and .mly.201607)
library(cleanIGRA)
filepath <- system.file("extdata//v1", "61902.y2d", package = "cleanIGRA")  
mydata <- clean_IGRA_v1(filepath)
```

```{r}
DT::datatable(head(mydata, 100), options = list(scrollX = TRUE,  pageLength = 5))  # show results
```


#### IGRA v2 data
```{r, results = 'hide', cache = TRUE}
# IGRA v2 data (.txt)
library(cleanIGRA)
filepath <- system.file("extdata//v2", "ASM00094703-data.txt", package = "cleanIGRA")
mydata <- clean_IGRA_v2(filepath)
```

```{r}
DT::datatable(head(mydata, 100), options = list(scrollX = TRUE,  pageLength = 5))  # show results
```
